echo 'Cleaning GloVe junk...'

# Junk generated by GloVe
rm -f glove/2matlab
rm -f glove/cooccurrence.bin
rm -f glove/cooccurrence.shuf.bin
rm -f glove/vectors.bin
rm -f glove/vectors.txt
rm -f glove/vocab.txt

# Junk generated by bigramify
rm -f glove/vocab_bi.txt
rm -f glove/text8_bi

echo 'Done cleaning'